apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tuan-spring-boot-websocket-chat-demo
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: tuan-spring-boot-websocket-chat-demo
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: tuan-spring-boot-websocket-chat-demo
        image: devops20190715.azurecr.io/tuan-spring-boot-websocket-chat-demo:kube1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: tuan-spring-boot-websocket-chat-demo
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: tuan-spring-boot-websocket-chat-demo
